### ISSUE TITLE
Closed captions 

### ISSUE THREAD

**Issue by mprh39** [cguZZman/repository.plugins#1] opened 2018-09-12 17:50 UTC
Why hasn't somebody come up with a easy way to  get subtitles and open subtitles.org on the programming. ?
I am confused setting up subtitles with every provider.

Thank you

**Comment by cguZZman** [comment] 2018-09-12 22:04
Not sure what the problem is and not sure how that relates to this repository project. So, closing this up.

**Closed by cguZZman** 2018-09-12 22:04 UTC

**Comment by mprh39** [comment] 2018-09-13 01:51
Sorry.

Is there a plug-in available  that would automatically  up date subtitles
for all the add-ons? Instead of having to manually set up? I must update
each and everyone of my plug-ins. Most of the add-ons do not have a
separate tool function for this.

Thank you for your help,

Marie Hanerkam

**Comment by cguZZman** [comment] 2018-09-13 23:40
There is an option in kodi which automatically search and assign a subtitle from the provider previously configured. Make a quick google search and it should pop up.
It's not the same functionality as the one I added to the cloud drive addons, which assigns a subtitle automatically from your own cloud drive.
